name: Deploy to Dev Server (Alternative - No Sudo)

on:
  push:
    branches: [ dev ]
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Navigate to your project directory
          cd ${{ secrets.PROJECT_PATH }}
          
          # Alternative: Reset Git state without sudo
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          
          # Force reset to avoid permission issues
          git reset --hard HEAD
          git clean -fd
          
          # Pull latest changes from dev branch
          git pull origin dev
          
          # Optional: Install dependencies if package.json changed
          if [ -f "pnpm-lock.yaml" ] && [ -f "package.json" ]; then
            echo "Checking for dependency changes..."
            if [ ! -d "node_modules" ] || [ "pnpm-lock.yaml" -nt "node_modules" ]; then
              echo "Dependencies changed or missing, installing..."
              pnpm install
            else
              echo "Dependencies up to date"
            fi
          fi
          
          # Optional: Restart your application (uncomment if needed)
          # pm2 restart mongoweb || pnpm start
          
          echo "Deployment completed successfully!"
