name: Deploy to Server

on:
  push:
    branches: [ dev, main, master ]
  pull_request:
    types: [closed]
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          echo "Current directory: $(pwd)"
          
          # Fix Git directory permissions
          echo "Fixing Git directory permissions..."
          sudo chown -R $(whoami):$(whoami) .git/ 2>/dev/null || true
          chmod -R 755 .git/ 2>/dev/null || true
          
          # Configure Git safe directory
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          
          # Check if this is a Git repository
          if [ ! -d ".git" ]; then
            echo "Not a Git repository. Initializing..."
            git init
            git remote add origin https://github.com/brtprivate/dev_db.git
          fi
          
          # Ensure remote is configured correctly
          git remote set-url origin https://github.com/brtprivate/dev_db.git
          
          # Fetch all references first
          echo "Fetching latest changes..."
          git fetch origin
          
          # Check if master branch exists remotely
          if git ls-remote --heads origin master | grep -q master; then
            echo "Master branch found. Attempting pull..."
            if git pull origin master; then
              echo "Git pull successful"
            else
              echo "Git pull failed. Trying reset..."
              git reset --hard origin/master
            fi
          else
            echo "Master branch not found. Checking available branches..."
            git ls-remote --heads origin
            echo "Trying to pull from main branch instead..."
            if git pull origin main; then
              echo "Git pull from main successful"
            else
              echo "No suitable branch found for deployment"
              exit 1
            fi
          fi
          
          echo "Deployment completed successfully!"
