name: Deploy to Server

on:
  push:
    branches: [dev, main, master]
  pull_request:
    types: [closed]
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          echo "🚀 Starting deployment..."
          cd ${{ secrets.PROJECT_PATH }} || { echo "❌ Invalid project path"; exit 1; }

          echo "📂 Current directory: $(pwd)"
          echo "👤 Current user: $(whoami)"

          # Make sure the git repo is valid
          if [ ! -d ".git" ]; then
            echo "❌ No .git directory found. Cloning fresh repository..."
            cd ..
            git clone https://github.com/brtprivate/dev_db.git "$(basename ${{ secrets.PROJECT_PATH }})"
            cd "$(basename ${{ secrets.PROJECT_PATH }})"
          fi

          # Configure git safety and remote URL
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          git remote remove origin 2>/dev/null || true
          git remote add origin https://github.com/brtprivate/dev_db.git

          echo "🧹 Cleaning workspace..."
          git reset --hard HEAD
          git clean -fd

          echo "🌿 Fetching and pulling latest changes..."
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD || echo "master")
          git fetch origin $CURRENT_BRANCH || { echo "❌ Fetch failed"; exit 1; }
          git checkout $CURRENT_BRANCH || git checkout -b $CURRENT_BRANCH origin/$CURRENT_BRANCH
          git pull origin $CURRENT_BRANCH || { echo "❌ Pull failed"; exit 1; }

          echo "✅ Git pull successful."
          echo "🧩 Latest commit:"
          git log -1 --oneline

          echo "⚙️ Running post-deploy steps..."
          # Example: npm install && npm run build
          # Uncomment if needed:
          # npm ci --omit=dev
          # npm run build

          echo "✅ Deployment completed successfully!"
