name: Deploy to Server

on:
  push:
    branches: [ dev, main, master ]
  pull_request:
    types: [closed]
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          echo "Current directory: $(pwd)"
          git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
          echo "Attempting git pull from master..."
          if git pull origin master; then
            echo "Git pull successful"
          else
            echo "Git pull failed. Trying reset..."
            git fetch origin master
            git reset --hard origin/master
          fi
          echo "Deployment completed successfully!"
