name: SonarQube Analysis (Minimal)

on:
  push:
    branches: [ dev, main, master ]
  pull_request:
    branches: [ dev, main, master ]
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install

    - name: Run SonarQube Scanner
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=db \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.exclusions=node_modules/**,coverage/**,*.md,*.yml,*.yaml,.github/**
